apiVersion: v1
kind: Service
metadata:
  name: lifeos-frontend
  namespace: lifeos
  labels:
    app: lifeos-frontend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: lifeos-frontend
  sessionAffinity: None